
$font = SpaceMono Nerd Font Mono

general {
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = screenshot
    blur_size = 6
    blur_passes = 3
    color = rgb(2, 7, 24)
    brightness = 0.22
    contrast = 0.82
    noise = 0.008
}

label {
    monitor =
    text = $TIME
    font_family = $font
    font_size = 104
    color = rgb(25, 93, 238)

    position = 0, 190
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +'%A, %d %B %Y'
    font_family = $font
    font_size = 25
    color = rgb(22, 56, 138)

    position = 0, 92
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 430, 58
    position = 0, -50
    halign = center
    valign = center
    force_show = true

    outline_thickness = 1
    rounding = 0
    fade_on_empty = false

    font_family = $font
    font_color = rgb(58, 128, 238)
    inner_color = rgba(1, 5, 18, 0.14)
    outer_color = rgb(28, 92, 210)
    check_color = rgb(58, 128, 238)
    fail_color = rgb(255, 120, 120)

    placeholder_text =
    fail_text = authentication failed
    fail_transition = 0
}

label {
    monitor =
    text = cmd[update:0] echo "user: $(whoami)"
    font_family = $font
    font_size = 22
    color = rgb(28, 70, 160)

    position = 0, 12
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[EN,RU]
    font_family = $font
    font_size = 22
    color = rgb(22, 56, 138)

    position = 0, -108
    halign = center
    valign = center
}
